### ISSUE TITLE
Не работает под osx

### ISSUE THREAD

**Issue by broderix** [TheDrHax/mosmetro-auth#9]
```
$ python --version
Python 2.7.11

$ pip show requests

---
Metadata-Version: 2.0
Name: requests
Version: 2.9.1
Summary: Python HTTP for Humans.
Home-page: http://python-requests.org
Author: Kenneth Reitz
Author-email: me@kennethreitz.com
License: Apache 2.0
Location: /usr/local/lib/python2.7/site-packages
```

```
2016-04-26 08:54:07.655290
/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Connecting...
/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Traceback (most recent call last):
  File "/Users/broderix/Downloads/metro.py", line 73, in <module>
    connect(url_auth)
  File "/Users/broderix/Downloads/metro.py", line 43, in connect
    page_auth.content, re.DOTALL).group(0))
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by TheDrHax** [comment]
Эта ошибка проявляется каждый раз или вы только один раз пробовали? Просто я только что проверил скрипт с телефона и он сработал (я думал, что он устарел уже).

Суть в том, что у вас сервер, похоже, не вернул страницу авторизации (или вернул, но что-то не то).

**Comment by broderix** [comment]
появляется каждый раз, но похоже что авторизация работает

**Comment by TheDrHax** [comment]
Добавил вывод кода полученной страницы в лог. Думаю, это может помочь с определением причины проблемы.

**Comment by TheDrHax** [comment]
Теперь скрипт не использует регулярные выражения, так что именно этой проблемы больше быть не должно.
